logging:
  level:
    root: INFO
#    org:
#      springframework: ERROR
#        web: INFO
#          filter: DEBUG
#        boot:
#          autoconfigure: INFO
  file:
    path: C:\log
    name: ${logging.file.path}/reserves.log

  logback:
    rollingpolicy:
      clean-history-on-start: false
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 1MB
      max-history: 7

spring:
  codec:
    log-request-details: true