logging:
  file:
    path: C:\log
    name: ${logging.file.path}/reserves.log
  level:
    root: INFO
#    org:
#      springframework:
#        jdbc:
#          core:
#            JdbcTemplate: ERROR
#            StatementCreatorUtils: ERROR
#      hibernate:
#        dialect:
#          H2Dialect: ERROR
#      hibernate:
#        SQL: INFO
#        type:
#          descriptor:
#            sql: INFO
#    org:
#      springframework: ERROR
#        web: INFO
#          filter: DEBUG
#        boot:
#          autoconfigure: INFO
  logback:
    rollingpolicy:
      clean-history-on-start: false
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
      max-file-size: 1MB
      max-history: 7
  register-shutdown-hook: false

spring:
  codec:
    log-request-details: true